version: '3.3'
services:
    demo_db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            PGDATA: /tmp/demo_data
        volumes:
            - postgres_data:/tmp/demo_data
        restart: "always"
    web:
        build: .
        command: >
            bash -c "sleep 10 &&
            python manage.py showmigrations &&
            python manage.py makemigrations &&
            python manage.py collectstatic --no-input --clear &&
            gunicorn demo.wsgi:application --timeout 120 --bind 0.0.0.0:8000"
        volumes:
            - .:/docker:rw
            - static_volume:/home/ubuntu/docker/staticfiles/
        ports:
            - 8080:8000
        depends_on:
            - demo_db
        restart: "always"    
volumes:
    postgres_data:
    static_volume:
        

